#!/bin/bash

# This client is executed by the service /etc/systemd/system/showcast.service

eval "$(conda shell.bash hook)"

#/home/satellite/miniconda3/condabin/conda init bash

/home/satellite/miniconda3/condabin/conda activate showcast

cd /var/www/html/SHOWCast.GR/Scripts/

python showcast_start.py
